stages:
  - test
  - deploy

image: node:14.17.0-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: test
  script:
    - npm run lint

prettier:
  stage: test
  script:
    - npm run check:format

deploy:
  stage: deploy
  script:
    - eval${ssh-agent -s}
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh